import margheritaPizzaImg from '@/assets/recipes/margherita-pizza.jpg';
import misoRamenImg from '@/assets/recipes/miso-ramen.jpg';
import pancakesImg from '@/assets/recipes/pancakes.jpg';
import tikkaMasalaImg from '@/assets/recipes/tikka-masala.jpg';
import tiramisuImg from '@/assets/recipes/tiramisu.jpg';
import padThaiImg from '@/assets/recipes/pad-thai.jpg';
import tacosAlPastorImg from '@/assets/recipes/tacos-al-pastor.jpg';
import guacamoleImg from '@/assets/recipes/guacamole.jpg';
import beefBourguignonImg from '@/assets/recipes/beef-bourguignon.jpg';
import croissantsImg from '@/assets/recipes/croissants.jpg';
import greekSaladImg from '@/assets/recipes/greek-salad.jpg';
import falafelImg from '@/assets/recipes/falafel.jpg';
import kungPaoChickenImg from '@/assets/recipes/kung-pao-chicken.jpg';
import dimSumImg from '@/assets/recipes/dim-sum.jpg';
import chickenShawarmaImg from '@/assets/recipes/chicken-shawarma.jpg';
import baklavaImg from '@/assets/recipes/baklava.jpg';

export interface Recipe {
  id: string;
  title: string;
  description: string;
  image: string;
  cuisine: string;
  mealType: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  ingredients: string[];
  instructions: string[];
  createdAt: string;
}

export const cuisines = [
  'Italian',
  'Mexican',
  'Japanese',
  'Indian',
  'French',
  'Thai',
  'Mediterranean',
  'American',
  'Chinese',
  'Middle Eastern',
] as const;

export const mealTypes = [
  'Breakfast',
  'Lunch',
  'Dinner',
  'Dessert',
  'Appetizer',
  'Snack',
  'Side Dish',
] as const;

export const difficulties = ['Easy', 'Medium', 'Hard'] as const;

// Sample recipes data
export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Classic Margherita Pizza',
    description: 'A traditional Italian pizza with fresh mozzarella, tomatoes, and basil on a crispy thin crust.',
    image: margheritaPizzaImg,
    cuisine: 'Italian',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      '2 1/4 cups all-purpose flour',
      '1 packet active dry yeast',
      '1 cup warm water',
      '1 tbsp olive oil',
      '1 tsp salt',
      '1 cup crushed San Marzano tomatoes',
      '8 oz fresh mozzarella',
      'Fresh basil leaves',
      'Extra virgin olive oil for drizzling',
    ],
    instructions: [
      'Dissolve yeast in warm water and let sit for 5 minutes until foamy.',
      'Mix flour and salt, then add yeast mixture and olive oil. Knead for 10 minutes.',
      'Let dough rise for 1 hour in a warm place.',
      'Preheat oven to 500°F (260°C) with a pizza stone if available.',
      'Stretch dough into a 12-inch circle on floured surface.',
      'Spread crushed tomatoes, leaving a 1-inch border.',
      'Add torn mozzarella pieces and bake for 12-15 minutes.',
      'Top with fresh basil and drizzle with olive oil before serving.',
    ],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Japanese Miso Ramen',
    description: 'Rich and savory miso-based ramen with tender chashu pork, soft-boiled eggs, and fresh vegetables.',
    image: misoRamenImg,
    cuisine: 'Japanese',
    mealType: 'Dinner',
    prepTime: 45,
    cookTime: 120,
    servings: 4,
    difficulty: 'Hard',
    ingredients: [
      '4 portions fresh ramen noodles',
      '8 cups pork or chicken broth',
      '1/4 cup white miso paste',
      '2 tbsp soy sauce',
      '1 tbsp sesame oil',
      '4 soft-boiled eggs',
      '8 slices chashu pork',
      'Green onions, sliced',
      'Nori sheets',
      'Bean sprouts',
    ],
    instructions: [
      'Prepare the chashu pork a day ahead by braising pork belly in soy sauce, mirin, and sake.',
      'Soft boil eggs for 6.5 minutes, then marinate in soy sauce mixture.',
      'Heat broth and whisk in miso paste until dissolved.',
      'Add soy sauce and sesame oil to taste.',
      'Cook ramen noodles according to package directions.',
      'Divide noodles among bowls and ladle hot broth over.',
      'Top with chashu, egg halves, green onions, nori, and bean sprouts.',
      'Serve immediately while piping hot.',
    ],
    createdAt: '2024-01-20',
  },
  {
    id: '3',
    title: 'Fluffy Pancakes',
    description: 'Light and fluffy American-style pancakes perfect for a lazy weekend breakfast.',
    image: pancakesImg,
    cuisine: 'American',
    mealType: 'Breakfast',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      '2 cups all-purpose flour',
      '2 tbsp sugar',
      '2 tsp baking powder',
      '1 tsp baking soda',
      '1/2 tsp salt',
      '2 cups buttermilk',
      '2 eggs',
      '1/4 cup melted butter',
      'Maple syrup and butter for serving',
    ],
    instructions: [
      'Whisk together flour, sugar, baking powder, baking soda, and salt.',
      'In another bowl, whisk buttermilk, eggs, and melted butter.',
      'Pour wet ingredients into dry and stir until just combined (lumps are okay).',
      'Heat a griddle or pan over medium heat and lightly grease.',
      'Pour 1/4 cup batter per pancake.',
      'Cook until bubbles form on surface, then flip and cook 2 more minutes.',
      'Keep warm in a 200°F oven while cooking remaining pancakes.',
      'Serve stacked with butter and maple syrup.',
    ],
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    title: 'Chicken Tikka Masala',
    description: 'Tender chicken pieces in a creamy, spiced tomato sauce. A beloved Indian-British fusion dish.',
    image: tikkaMasalaImg,
    cuisine: 'Indian',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 40,
    servings: 6,
    difficulty: 'Medium',
    ingredients: [
      '2 lbs boneless chicken thighs',
      '1 cup yogurt',
      '2 tbsp garam masala',
      '1 tbsp turmeric',
      '1 tbsp cumin',
      '1 can crushed tomatoes',
      '1 cup heavy cream',
      '2 onions, diced',
      '4 cloves garlic, minced',
      '2 inch ginger, grated',
      'Fresh cilantro',
    ],
    instructions: [
      'Marinate chicken in yogurt and half the spices for at least 2 hours.',
      'Grill or broil marinated chicken until charred and cooked through.',
      'Sauté onions until golden, then add garlic and ginger.',
      'Add remaining spices and cook for 1 minute until fragrant.',
      'Pour in crushed tomatoes and simmer for 15 minutes.',
      'Stir in heavy cream and simmer 10 more minutes.',
      'Cut grilled chicken into pieces and add to sauce.',
      'Garnish with fresh cilantro and serve with basmati rice.',
    ],
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    title: 'Tiramisu',
    description: 'Classic Italian layered dessert with espresso-soaked ladyfingers and mascarpone cream.',
    image: tiramisuImg,
    cuisine: 'Italian',
    mealType: 'Dessert',
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: 'Medium',
    ingredients: [
      '6 egg yolks',
      '3/4 cup sugar',
      '16 oz mascarpone cheese',
      '2 cups heavy cream',
      '2 cups strong espresso, cooled',
      '3 tbsp coffee liqueur',
      '24 ladyfinger cookies',
      'Cocoa powder for dusting',
    ],
    instructions: [
      'Whisk egg yolks and sugar until thick and pale yellow.',
      'Add mascarpone and mix until smooth.',
      'In separate bowl, whip heavy cream to stiff peaks.',
      'Fold whipped cream into mascarpone mixture.',
      'Combine espresso and coffee liqueur in a shallow dish.',
      'Quickly dip ladyfingers in coffee mixture and layer in dish.',
      'Spread half the mascarpone cream over ladyfingers.',
      'Repeat layers and refrigerate at least 4 hours.',
      'Dust generously with cocoa powder before serving.',
    ],
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    title: 'Pad Thai',
    description: 'Sweet, sour, and savory Thai stir-fried rice noodles with shrimp, peanuts, and lime.',
    image: padThaiImg,
    cuisine: 'Thai',
    mealType: 'Dinner',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      '8 oz rice noodles',
      '1 lb shrimp, peeled',
      '3 tbsp fish sauce',
      '2 tbsp tamarind paste',
      '2 tbsp brown sugar',
      '2 eggs',
      '1 cup bean sprouts',
      '4 green onions',
      '1/2 cup roasted peanuts',
      'Lime wedges',
      'Fresh cilantro',
    ],
    instructions: [
      'Soak rice noodles in warm water for 30 minutes, then drain.',
      'Mix fish sauce, tamarind paste, and brown sugar for the sauce.',
      'Heat oil in wok over high heat and cook shrimp until pink. Set aside.',
      'Scramble eggs in the wok, then add noodles.',
      'Pour sauce over noodles and toss until coated.',
      'Add bean sprouts and green onions, toss briefly.',
      'Return shrimp to wok and mix everything together.',
      'Serve topped with crushed peanuts, cilantro, and lime wedges.',
    ],
    createdAt: '2024-02-20',
  },
  {
    id: '7',
    title: 'Tacos al Pastor',
    description: 'Authentic Mexican street tacos with marinated pork, fresh pineapple, and cilantro on corn tortillas.',
    image: tacosAlPastorImg,
    cuisine: 'Mexican',
    mealType: 'Dinner',
    prepTime: 30,
    cookTime: 25,
    servings: 6,
    difficulty: 'Medium',
    ingredients: [
      '2 lbs pork shoulder, thinly sliced',
      '4 dried guajillo chilies',
      '2 dried ancho chilies',
      '1/2 cup pineapple juice',
      '4 cloves garlic',
      '1 tsp cumin',
      '1 tsp oregano',
      '1/2 fresh pineapple, diced',
      '12 small corn tortillas',
      'White onion, diced',
      'Fresh cilantro',
      'Lime wedges',
    ],
    instructions: [
      'Toast dried chilies in a dry pan until fragrant, then soak in hot water for 20 minutes.',
      'Blend chilies with pineapple juice, garlic, cumin, and oregano to make marinade.',
      'Marinate pork slices for at least 2 hours, preferably overnight.',
      'Grill or pan-fry pork until charred and cooked through.',
      'Grill pineapple pieces until caramelized.',
      'Warm corn tortillas on the grill or in a dry pan.',
      'Chop pork into small pieces and serve on tortillas.',
      'Top with grilled pineapple, onion, cilantro, and a squeeze of lime.',
    ],
    createdAt: '2024-02-25',
  },
  {
    id: '8',
    title: 'Fresh Guacamole',
    description: 'Creamy, zesty Mexican guacamole made with ripe avocados, lime, and fresh cilantro.',
    image: guacamoleImg,
    cuisine: 'Mexican',
    mealType: 'Appetizer',
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: 'Easy',
    ingredients: [
      '4 ripe avocados',
      '1/2 red onion, finely diced',
      '2 Roma tomatoes, diced',
      '1 jalapeño, seeded and minced',
      '1/4 cup fresh cilantro, chopped',
      '2 limes, juiced',
      '1 tsp salt',
      '1/2 tsp cumin',
      'Tortilla chips for serving',
    ],
    instructions: [
      'Cut avocados in half and remove pits.',
      'Scoop avocado flesh into a bowl and mash with a fork to desired consistency.',
      'Add lime juice immediately to prevent browning.',
      'Fold in onion, tomatoes, jalapeño, and cilantro.',
      'Season with salt and cumin, adjusting to taste.',
      'Let flavors meld for 10 minutes before serving.',
      'Serve with fresh tortilla chips.',
    ],
    createdAt: '2024-03-01',
  },
  {
    id: '9',
    title: 'Beef Bourguignon',
    description: 'Classic French stew with tender beef braised in red wine with mushrooms, pearl onions, and carrots.',
    image: beefBourguignonImg,
    cuisine: 'French',
    mealType: 'Dinner',
    prepTime: 45,
    cookTime: 180,
    servings: 6,
    difficulty: 'Hard',
    ingredients: [
      '3 lbs beef chuck, cut into 2-inch cubes',
      '1 bottle dry red wine (Burgundy preferred)',
      '6 oz bacon, diced',
      '1 lb pearl onions',
      '1 lb cremini mushrooms',
      '4 carrots, sliced',
      '4 cloves garlic, minced',
      '2 tbsp tomato paste',
      '2 cups beef broth',
      'Fresh thyme and bay leaves',
      '2 tbsp flour',
    ],
    instructions: [
      'Pat beef dry and season generously with salt and pepper.',
      'Cook bacon in a Dutch oven until crispy, set aside.',
      'Brown beef in batches in the bacon fat, then set aside.',
      'Sauté carrots and pearl onions until lightly browned.',
      'Add garlic and tomato paste, cook for 1 minute.',
      'Sprinkle flour over vegetables and stir.',
      'Add wine, broth, thyme, bay leaves, bacon, and beef.',
      'Cover and braise in 325°F oven for 2.5-3 hours until beef is tender.',
      'Sauté mushrooms separately and add before serving.',
      'Serve over mashed potatoes or with crusty bread.',
    ],
    createdAt: '2024-03-05',
  },
  {
    id: '10',
    title: 'French Croissants',
    description: 'Buttery, flaky French pastries with delicate layers. Perfect for a special breakfast.',
    image: croissantsImg,
    cuisine: 'French',
    mealType: 'Breakfast',
    prepTime: 120,
    cookTime: 20,
    servings: 12,
    difficulty: 'Hard',
    ingredients: [
      '4 cups all-purpose flour',
      '1/3 cup sugar',
      '1 tbsp salt',
      '2 1/4 tsp active dry yeast',
      '1 1/4 cups cold milk',
      '1 1/2 cups cold unsalted butter',
      '1 egg for egg wash',
    ],
    instructions: [
      'Mix flour, sugar, salt, and yeast. Add milk and mix until dough forms.',
      'Knead briefly and refrigerate for 1 hour.',
      'Pound butter into a flat rectangle between parchment.',
      'Roll dough into rectangle twice the size of butter.',
      'Encase butter in dough and seal edges.',
      'Roll out and fold into thirds (book fold). Refrigerate 1 hour.',
      'Repeat rolling and folding 3 more times, chilling between each.',
      'Roll final dough to 1/4 inch thick and cut into triangles.',
      'Roll each triangle from base to tip and curve into crescent.',
      'Proof for 2 hours until doubled, brush with egg wash.',
      'Bake at 400°F for 15-20 minutes until golden brown.',
    ],
    createdAt: '2024-03-10',
  },
  {
    id: '11',
    title: 'Greek Salad',
    description: 'Fresh Mediterranean salad with crisp vegetables, tangy feta cheese, and olive oil dressing.',
    image: greekSaladImg,
    cuisine: 'Mediterranean',
    mealType: 'Side Dish',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      '4 large ripe tomatoes, cut into wedges',
      '1 English cucumber, sliced',
      '1 red onion, thinly sliced',
      '1 green bell pepper, sliced',
      '1 cup Kalamata olives',
      '8 oz feta cheese block',
      '1/4 cup extra virgin olive oil',
      '2 tbsp red wine vinegar',
      '1 tsp dried oregano',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Cut tomatoes into large wedges and place in a large bowl.',
      'Add sliced cucumber, red onion, and bell pepper.',
      'Scatter Kalamata olives over vegetables.',
      'Place the block of feta cheese on top.',
      'Drizzle generously with olive oil and red wine vinegar.',
      'Sprinkle with dried oregano, salt, and pepper.',
      'Serve immediately without tossing to preserve presentation.',
    ],
    createdAt: '2024-03-15',
  },
  {
    id: '12',
    title: 'Crispy Falafel',
    description: 'Golden, crispy chickpea fritters served with creamy hummus and warm pita bread.',
    image: falafelImg,
    cuisine: 'Mediterranean',
    mealType: 'Lunch',
    prepTime: 30,
    cookTime: 15,
    servings: 6,
    difficulty: 'Medium',
    ingredients: [
      '2 cups dried chickpeas, soaked overnight',
      '1 onion, roughly chopped',
      '4 cloves garlic',
      '1 cup fresh parsley',
      '1/2 cup fresh cilantro',
      '1 tsp cumin',
      '1 tsp coriander',
      '1/4 tsp cayenne pepper',
      '1 tsp salt',
      '1 tsp baking powder',
      'Oil for frying',
      'Pita bread and tahini for serving',
    ],
    instructions: [
      'Drain soaked chickpeas thoroughly (do not use canned).',
      'Pulse chickpeas, onion, garlic, and herbs in food processor until finely ground.',
      'Add spices, salt, and baking powder. Mix well.',
      'Refrigerate mixture for 1 hour to firm up.',
      'Form into small patties or balls using wet hands.',
      'Heat oil to 350°F for deep frying.',
      'Fry falafel in batches for 3-4 minutes until deep golden brown.',
      'Drain on paper towels and serve with pita, hummus, and tahini.',
    ],
    createdAt: '2024-03-20',
  },
  {
    id: '13',
    title: 'Kung Pao Chicken',
    description: 'Spicy Sichuan stir-fry with tender chicken, roasted peanuts, and dried red chilies in a savory sauce.',
    image: kungPaoChickenImg,
    cuisine: 'Chinese',
    mealType: 'Dinner',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      '1.5 lbs boneless chicken thighs, cubed',
      '1/2 cup roasted peanuts',
      '10-12 dried red chilies',
      '3 green onions, chopped',
      '4 cloves garlic, minced',
      '1 inch ginger, minced',
      '3 tbsp soy sauce',
      '2 tbsp Chinese black vinegar',
      '1 tbsp hoisin sauce',
      '1 tsp sugar',
      '1 tbsp cornstarch',
      '2 tbsp Shaoxing wine',
    ],
    instructions: [
      'Marinate chicken with 1 tbsp soy sauce, wine, and cornstarch for 15 minutes.',
      'Mix remaining soy sauce, vinegar, hoisin, and sugar for the sauce.',
      'Heat wok over high heat, add oil and stir-fry chicken until golden. Remove.',
      'Add dried chilies to wok and stir until fragrant and darkened.',
      'Add garlic and ginger, stir-fry for 30 seconds.',
      'Return chicken to wok, pour in sauce and toss.',
      'Add peanuts and green onions, toss everything together.',
      'Serve immediately over steamed rice.',
    ],
    createdAt: '2024-03-25',
  },
  {
    id: '14',
    title: 'Dim Sum Dumplings',
    description: 'Delicate steamed dumplings with juicy pork filling, a classic Chinese tea house favorite.',
    image: dimSumImg,
    cuisine: 'Chinese',
    mealType: 'Appetizer',
    prepTime: 45,
    cookTime: 12,
    servings: 6,
    difficulty: 'Hard',
    ingredients: [
      '1 lb ground pork',
      '1/4 lb raw shrimp, minced',
      '2 tbsp soy sauce',
      '1 tbsp sesame oil',
      '1 tbsp Shaoxing wine',
      '1 tsp ginger, grated',
      '2 green onions, minced',
      '1 package round dumpling wrappers',
      'Cabbage leaves for steaming',
      'Chili oil and soy sauce for dipping',
    ],
    instructions: [
      'Mix pork, shrimp, soy sauce, sesame oil, wine, ginger, and green onions.',
      'Stir vigorously in one direction until mixture becomes sticky.',
      'Place a heaping teaspoon of filling in center of each wrapper.',
      'Wet edges with water and pleat wrapper around filling.',
      'Line bamboo steamer with cabbage leaves or parchment.',
      'Arrange dumplings in steamer, leaving space between each.',
      'Steam over boiling water for 10-12 minutes until cooked through.',
      'Serve hot with chili oil and soy sauce for dipping.',
    ],
    createdAt: '2024-03-30',
  },
  {
    id: '15',
    title: 'Chicken Shawarma',
    description: 'Aromatic Middle Eastern spiced chicken with garlic sauce, served with rice and warm pita.',
    image: chickenShawarmaImg,
    cuisine: 'Middle Eastern',
    mealType: 'Dinner',
    prepTime: 25,
    cookTime: 20,
    servings: 6,
    difficulty: 'Medium',
    ingredients: [
      '2 lbs boneless chicken thighs',
      '1/4 cup olive oil',
      '4 cloves garlic, minced',
      '2 tsp cumin',
      '2 tsp paprika',
      '1 tsp turmeric',
      '1 tsp coriander',
      '1/2 tsp cinnamon',
      '1/4 tsp cayenne pepper',
      'Juice of 2 lemons',
      'Garlic sauce (toum)',
      'Pickled turnips and pita bread',
    ],
    instructions: [
      'Mix olive oil, garlic, all spices, and lemon juice to make marinade.',
      'Coat chicken thoroughly and marinate for at least 4 hours, preferably overnight.',
      'Preheat grill or broiler to high heat.',
      'Grill chicken 5-6 minutes per side until charred and cooked through.',
      'Let rest for 5 minutes, then slice thinly against the grain.',
      'Prepare garlic sauce by blending garlic, oil, lemon, and salt.',
      'Serve chicken over rice with garlic sauce, pickled vegetables, and warm pita.',
    ],
    createdAt: '2024-04-01',
  },
  {
    id: '16',
    title: 'Baklava',
    description: 'Sweet Middle Eastern pastry with layers of phyllo, honey syrup, and chopped pistachios.',
    image: baklavaImg,
    cuisine: 'Middle Eastern',
    mealType: 'Dessert',
    prepTime: 45,
    cookTime: 50,
    servings: 24,
    difficulty: 'Hard',
    ingredients: [
      '1 lb phyllo dough',
      '1 lb unsalted butter, melted',
      '3 cups mixed nuts (pistachios, walnuts, almonds), chopped',
      '1 tsp cinnamon',
      '1/4 tsp cardamom',
      '1 1/2 cups sugar',
      '1 cup water',
      '1 cup honey',
      '1 tbsp lemon juice',
      '1 tsp rose water (optional)',
    ],
    instructions: [
      'Preheat oven to 350°F. Brush a 9x13 baking pan with butter.',
      'Mix chopped nuts with cinnamon and cardamom.',
      'Layer 8 sheets of phyllo in pan, brushing each with butter.',
      'Spread 1/3 of nut mixture evenly over phyllo.',
      'Repeat layering: 6 sheets with butter, nuts, 6 sheets, nuts, 8 top sheets.',
      'Cut into diamond shapes before baking.',
      'Bake for 45-50 minutes until golden brown and crispy.',
      'While baking, simmer sugar, water, and honey for 10 minutes. Add lemon juice.',
      'Pour cooled syrup over hot baklava immediately after removing from oven.',
      'Let cool completely for several hours before serving.',
    ],
    createdAt: '2024-04-05',
  },
];
